DROP TABLE IF EXISTS 'CATEGORIES';


CREATE TABLE Categories (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL UNIQUE,
description VARCHAR(30),
active SMALLINT(1) UNSIGNED NOT NULL,
creation_date TIMESTAMP NOT NULL,
delete_date TIMESTAMP
)