DROP TABLE IF EXISTS 'TRANSACTIONS';


CREATE TABLE Transactions (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
id_user INT(6) UNSIGNED NOT NULL,
id_item INT(6) UNSIGNED NOT NULL,
message VARCHAR(200),
FOREIGN KEY (id_user) REFERENCES users(id),
FOREIGN KEY (id_item) REFERENCES items(id)
);