package it.coluccia.shareit.dto.categories.shareitdb;

import java.io.Serializable;
import java.util.Date;

public class Categories implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.active
     *
     * @mbggenerated
     */
    private Short active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.creation_date
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.delete_date
     *
     * @mbggenerated
     */
    private Date deleteDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table categories
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.name
     *
     * @return the value of categories.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.name
     *
     * @param name the value for categories.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.description
     *
     * @return the value of categories.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.description
     *
     * @param description the value for categories.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.active
     *
     * @return the value of categories.active
     *
     * @mbggenerated
     */
    public Short getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.active
     *
     * @param active the value for categories.active
     *
     * @mbggenerated
     */
    public void setActive(Short active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.creation_date
     *
     * @return the value of categories.creation_date
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.creation_date
     *
     * @param creationDate the value for categories.creation_date
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.delete_date
     *
     * @return the value of categories.delete_date
     *
     * @mbggenerated
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.delete_date
     *
     * @param deleteDate the value for categories.delete_date
     *
     * @mbggenerated
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }
}